version: '3.5'

# Example stack for local development
# IMPORTANT: you need to create the docker images first via gradle like this:
# ./gradlew buildDockerImage

services:
  signpdf:
    image: lovelysystems/signpdf:dev
    ports:
     - "18080:5678"
    environment:
      # optional environment variables set here for reference
      KEYSTORE_PASS_PATH: /run/secrets/signpdf-keystore-pass
      KEYSTORE_PATH: /run/secrets/signpdf-keystore
      PORT: 5678
    volumes:
      # map the sample files used in tests as secrets
      - ../src/test/resources/com/lovelysystems/signpdf/samplekeystore.p12:/run/secrets/signpdf-keystore
      - ../src/test/resources/com/lovelysystems/signpdf/samplekeystorepass.txt:/run/secrets/signpdf-keystore-pass
